### PR TITLE
Create super-linter.yml

### PR DESCRIPTION
**Pull request by aniruddhaadak80**
**For issue #49**

### CODE REVIEW

**Comment by jbampton** [comment]
We already did this one. You git moved the file :)

https://github.com/brisbanesocialchess/.github/blob/main/.github/workflows/linter.yml

**Comment by aniruddhaadak80** [comment]
> We already did this one. You git moved the file :)
> 
> https://github.com/brisbanesocialchess/.github/blob/main/.github/workflows/linter.yml


But this PR is for fixing super-linter.yml accordig to issue #49 . Is't it ? 

Please clarify me .

**Comment by jbampton** [comment]
We have to fix the super linter errors

**Comment by jbampton** [comment]
https://github.com/brisbanesocialchess/.github/issues/64

**Pull request closed without merging**
