### PR TITLE
Update Codespellrc

### LINKED ISSUE #82: Fix codespell pre-commit
https://github.com/brisbanesocialchess/.github/actions/runs/11576753832/job/32226483810?pr=78

### PR DESCRIPTION
**Pull request by dhirajchaurasiya10**
**Description**
I updated .codespellrc file which might solve pre-commit
Fixes #82

### CODE REVIEW

**Review by jbampton — APPROVED** [review]
💃

**Comment by jbampton** [comment]
Thanks once again :100:

**Comment by dhirajchaurasiya10** [comment]
That's your favour for all precise guidance to solve the issue.💯

**Comment by jbampton** [comment]
Hey @dhirajchaurasiya10 

You can set your membership in the Brisbane Social Chess GitHub Organization to "public" on the people page when logged in:

https://github.com/orgs/brisbanesocialchess/people

Please show your support for your new team :)

If you are a private member, the public including everyone else that is not in the team won't see that you are part of Brisbane Social Chess.

Currently you can check your GitHub profile or the Brisbane Social Chess organization profile in a private tab or incognito window and you will see that your organization is not listed on your profile and that your avatar does not show on the Brisbane Social Chess organization homepage.

Your choice. Thanks once again !!

**Pull request merged**
